// Shell completion script output. Currently supports zsh only.
//
// Usage:
//   dora completion zsh > ~/.zfunc/_dora    # then add `fpath=(~/.zfunc $fpath)` and `autoload -U compinit; compinit`
//   eval "$(dora completion zsh)"            # session-only
import { writeLine } from "../render.js";

export function completion(shell: string): number {
  if (shell === "zsh") {
    writeLine(ZSH_SCRIPT);
    return 0;
  }
  process.stderr.write(`unsupported shell: ${shell} (supported: zsh)\n`);
  return 64;
}

const ZSH_SCRIPT = `#compdef dora
# zsh completion for dora. Generated by \`dora completion zsh\`.
# Install: \`dora completion zsh > ~/.zfunc/_dora\` and ensure the dir is on
# $fpath before \`compinit\`. Or for this shell only: \`eval "$(dora completion zsh)"\`.

_dora() {
  local context state line curcontext="$curcontext"

  _arguments -C \\
    '(-h --help)'{-h,--help}'[このヘルプを表示]' \\
    '(-V --version)'{-V,--version}'[バージョンを表示]' \\
    '(-p --prompt)'{-p,--prompt}'[自然言語の質問からコマンドを逆引き]:question:' \\
    '--full[FULL モード（全オプション逐語訳）]' \\
    '--man[ヘルプ取得元を man に強制]' \\
    '--raw[翻訳の下に原文も併記]' \\
    '--no-stream[ストリーミングを無効化]' \\
    '--debug[デバッグ情報を stderr へ]' \\
    '--dora[ドラえもん口調で出力]' \\
    '--no-cache[キャッシュを無効化]' \\
    '--refresh[キャッシュを無視して再生成]' \\
    '--no-think-bypass[思考バイパスを無効化]' \\
    '--no-tools[LLM のツール呼び出しを無効化]' \\
    '--max-tool-calls[ツール呼び出し上限]:count:' \\
    '--model[モデル ID を上書き]:id:' \\
    '--base-url[エンドポイントを上書き]:url:' \\
    '--provider[プロバイダ]:provider:(lm-studio claude codex)' \\
    '*--ctx[事前注入するコマンドのヘルプ]:cmd:_command_names' \\
    '1: :->first' \\
    '*:: :->rest' \\
    && return 0

  case $state in
    first)
      _alternative \\
        'subcommands:subcommand:((
          precache\\:"履歴 or 直接指定で事前キャッシュ"
          cache\\:"キャッシュ管理 (list/clear/path)"
          install-skill\\:"Claude Code 用スキルをインストール"
          completion\\:"シェル補完スクリプトを出力"
        ))' \\
        'commands:command:_command_names'
      ;;
    rest)
      case $line[1] in
        precache)
          _arguments \\
            '(-y --yes)'{-y,--yes}'[履歴読み取りと時間確認を自動承認]' \\
            '--dry-run[一覧のみ表示]' \\
            '--limit[最大件数]:n:' \\
            '--min-count[top-level 最低出現回数]:n:' \\
            '--pair-min-count[pair 最低出現回数]:n:' \\
            '--threshold[閾値分]:min:' \\
            '--auto-subs[auto sub 上限]:n:' \\
            '--history-file[履歴ファイル]:path:_files' \\
            '--tone[トーン]:tone:(default dora)' \\
            '--mode[モード]:mode:(summary full)' \\
            '--all[default/dora × summary/full の 4 variants]' \\
            '*:cmd:_command_names'
          ;;
        cache)
          _arguments \\
            '1:action:(list clear path)' \\
            '2:pattern:'
          ;;
        install-skill)
          _arguments \\
            '(-f --force)'{-f,--force}'[既存ファイルを上書き]' \\
            '--dir[インストール先]:path:_files -/'
          ;;
        completion)
          _arguments '1:shell:(zsh)'
          ;;
        *)
          # sub-args of a top-level command (for INTENT mode the last arg is a
          # free-form task description; fall back to file completion for
          # everything else).
          _files
          ;;
      esac
      ;;
  esac
}

_dora "$@"
`;
