// Shell completion script output. Currently supports zsh only.
//
// Usage:
//   helpdora completion zsh > ~/.zfunc/_helpdora    # then add `fpath=(~/.zfunc $fpath)` and `autoload -U compinit; compinit`
//   eval "$(helpdora completion zsh)"                # session-only
import { writeLine } from "../render.js";

export function completion(shell: string): number {
  if (shell === "zsh") {
    writeLine(ZSH_SCRIPT);
    return 0;
  }
  process.stderr.write(`unsupported shell: ${shell} (supported: zsh)\n`);
  return 64;
}

const ZSH_SCRIPT = `#compdef helpdora
# zsh completion for helpdora. Generated by \`helpdora completion zsh\`.
# Install: \`helpdora completion zsh > ~/.zfunc/_helpdora\` and ensure the dir is on
# $fpath before \`compinit\`. Or for this shell only: \`eval "$(helpdora completion zsh)"\`.
#
# fzf-tab friendly: uses tagged \`_describe\` groups so subcommands / values
# / external commands show as separate sections when fzf-tab is active.

_helpdora() {
  local context state line curcontext="$curcontext"
  local -a providers tones modes cache_actions shells subcmds

  providers=(
    'lm-studio:ローカル LM Studio (default)'
    'claude:Anthropic claude CLI 経由'
    'codex:OpenAI codex CLI 経由'
  )
  tones=('default:素の翻訳' 'dora:ドラえもん口調')
  modes=('summary:要点＋レシピ' 'full:全オプション逐語訳')
  cache_actions=(
    'list:エントリ一覧'
    'clear:部分一致で削除'
    'path:キャッシュディレクトリを表示'
  )
  shells=('zsh:zsh 補完スクリプト')
  subcmds=(
    'precache:履歴 or 直接指定で事前キャッシュ'
    'cache:キャッシュ管理 (list/clear/path)'
    'install-skill:Claude Code 用スキル'
    'completion:シェル補完スクリプトを出力'
  )

  _arguments -C \\
    '(-h --help)'{-h,--help}'[このヘルプを表示]' \\
    '(-V --version)'{-V,--version}'[バージョンを表示]' \\
    '(-p --prompt)'{-p,--prompt}'[自然言語の質問からコマンドを逆引き]:question:' \\
    '--full[FULL モード（全オプション逐語訳）]' \\
    '--man[ヘルプ取得元を man に強制]' \\
    '--raw[翻訳の下に原文も併記]' \\
    '--no-stream[ストリーミングを無効化]' \\
    '--debug[デバッグ情報を stderr へ]' \\
    '--dora[ドラえもん口調で出力]' \\
    '--no-cache[キャッシュを無効化]' \\
    '--refresh[キャッシュを無視して再生成]' \\
    '--no-think-bypass[思考バイパスを無効化]' \\
    '--no-tools[LLM のツール呼び出しを無効化]' \\
    '--max-tool-calls[ツール呼び出し上限]:count:' \\
    '--model[モデル ID を上書き]:id:' \\
    '--base-url[エンドポイントを上書き]:url:' \\
    '--provider[プロバイダ]:provider:->providers' \\
    '*--ctx[事前注入するコマンドのヘルプ]:cmd:->external_cmds' \\
    '1: :->first' \\
    '*:: :->rest' \\
    && return 0

  case $state in
    providers)
      _describe -t providers 'プロバイダ' providers
      ;;
    external_cmds)
      _command_names -e
      ;;
    first)
      # Show subcommands as their own group so fzf-tab separates them from
      # external commands.
      _describe -t subcommands 'helpdora サブコマンド' subcmds
      _alternative 'external-commands:コマンド:_command_names -e'
      ;;
    rest)
      case $line[1] in
        precache)
          _arguments \\
            '(-y --yes)'{-y,--yes}'[履歴読み取りと時間確認を自動承認]' \\
            '--dry-run[一覧のみ表示]' \\
            '--limit[最大件数]:n:' \\
            '--min-count[top-level 最低出現回数]:n:' \\
            '--pair-min-count[pair 最低出現回数]:n:' \\
            '--threshold[閾値分]:min:' \\
            '--auto-subs[auto sub 上限]:n:' \\
            '--history-file[履歴ファイル]:path:_files' \\
            '--tone[トーン]:tone:->tones' \\
            '--mode[モード]:mode:->modes' \\
            '--all[default/dora × summary/full の 4 variants]' \\
            '*:cmd:->external_cmds' \\
            && return 0
          case $state in
            tones) _describe -t tones 'トーン' tones ;;
            modes) _describe -t modes 'モード' modes ;;
            external_cmds) _command_names -e ;;
          esac
          ;;
        cache)
          _arguments \\
            '1:action:->cache_actions' \\
            '2:pattern:' \\
            && return 0
          case $state in
            cache_actions) _describe -t cache_actions 'アクション' cache_actions ;;
          esac
          ;;
        install-skill)
          _arguments \\
            '(-f --force)'{-f,--force}'[既存ファイルを上書き]' \\
            '--dir[インストール先]:path:_files -/'
          ;;
        completion)
          _arguments '1:shell:->shells' && return 0
          case $state in
            shells) _describe -t shells 'シェル' shells ;;
          esac
          ;;
        *)
          # Sub-args of an arbitrary top-level command. INTENT mode accepts
          # a free-form task description as last arg — we can't anticipate
          # that, so just offer file completion.
          _files
          ;;
      esac
      ;;
  esac
}

_helpdora "$@"
`;
